name       : endless-sky
version    : 0.9.2
release    : 1
source     :
    - https://github.com/endless-sky/endless-sky/archive/v0.9.2.tar.gz : aebf56be47448e8c29fd298b4e7124afc19c1078c9b5972f1f599e9957d79822
license    : GPL-3.0
component  : games.arcade
summary    : Endless Sky is a sandbox-style space exploration game similar to Elite, Escape Velocity, or Star Control.
description: |
    Endless Sky is a sandbox-style space exploration game similar to Elite, Escape Velocity, or Star Control.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - libjpeg-turbo-devel
    - scons
setup      : |
    sed -i "s|share/games|share|" SConstruct
    sed -i "s|share/games|share|" source/Files.cpp
    sed -i "s|/games|/bin|" SConstruct
build      : |
    scons DESTDIR=$installdir PREFIX=/usr
install    : |
    scons install DESTDIR=$installdir PREFIX=/usr
