name       : endless-sky
version    : 0.9.6
release    : 3
source     :
    - https://github.com/endless-sky/endless-sky/archive/v0.9.6.tar.gz : 41699dabb72a276c96019d0714e54492866e29661f161052a1caf334332be1e4
license    :
    - GPL-3.0
    - CC-BY-SA-4.0
    - CC-BY-SA-3.0
component  : games.arcade
summary    : Endless Sky is a sandbox-style space exploration game similar to Elite, Escape Velocity, or Star Control.
description: |
    Explore other star systems. Earn money by trading, carrying passengers, or
    completing missions. Use your earnings to buy a better ship or to upgrade the
    weapons and engines on your current one. Blow up pirates. Take sides in a civil
    war. Or leave human space behind and hope to find some friendly aliens whose
    culture is more civilized than your own...
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - libjpeg-turbo-devel
    - libmad-devel
    - scons
setup      : |
    sed -i "s|share/games|share|" SConstruct
    sed -i "s|share/games|share|" source/Files.cpp
    sed -i "s|/games|/bin|" SConstruct
build      : |
    scons %JOBS% DESTDIR=$installdir PREFIX=/usr
install    : |
    scons %JOBS% install DESTDIR=$installdir PREFIX=/usr
