name       : endless-sky
version    : 0.9.4
release    : 2
source     :
    - https://github.com/endless-sky/endless-sky/archive/v0.9.4.tar.gz : 8e25b9c387736d10034396940974cd442b8a7c6e9647a12c6d08fbeed9d32eeb
license    : GPL-3.0
component  : games.arcade
summary    : Endless Sky is a sandbox-style space exploration game similar to Elite, Escape Velocity, or Star Control.
description: |
    Endless Sky is a sandbox-style space exploration game similar to Elite, Escape Velocity, or Star Control.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - libjpeg-turbo-devel
    - scons
setup      : |
    sed -i "s|share/games|share|" SConstruct
    sed -i "s|share/games|share|" source/Files.cpp
    sed -i "s|/games|/bin|" SConstruct
build      : |
    scons DESTDIR=$installdir PREFIX=/usr
install    : |
    scons install DESTDIR=$installdir PREFIX=/usr
